# set global options for all zsh shells here
#

setopt nullglob

source /etc/profile.d/cnf.sh

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
